
strictness: high

uses:
  - django

requirements:
  - facsimile/requirements.txt


pep8:
  full: true
  options:
    hang-closing: 1
    max-line-length: 79

pylint:
  disable:
    - too-few-public-methods
