language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
branches:
  except:
    - gh-pages
env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0
matrix:
  fast_finish: true
  exclude:
    - python: "2.7"
      env: DJANGO=2.0
before_install:
  - sudo apt-get -qq update
install:
  - python -m pip install -U pip
  - python -m easy_install -U setuptools
  - pip install tox-travis codecov
script:
  - tox
after_success:
  - codecov -e DJANGO
