
language: python
python: 2.7
branches:
  except:
    - gh-pages
env:
  - TOX_ENV=py27-cov-init
  - TOX_ENV=py27-django18
  - TOX_ENV=py33-django18
  - TOX_ENV=py34-django18
  - TOX_ENV=py35-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py34-django19
  - TOX_ENV=py35-django19
  - TOX_ENV=py27-django110
  - TOX_ENV=py34-django110
  - TOX_ENV=py35-django110
  - TOX_ENV=py27-cov-report
before_install:
  - sudo apt-get -qq update
install:
  - python -m pip install -U pip
  - python -m easy_install -U setuptools
  - pip install tox
  - pip install codecov
script:
  - tox -e $TOX_ENV
after_success:
  - codecov
